export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST"
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS"
export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL"

export const AUTH_LOGOUT_REQUEST = "AUTH_LOGOUT_REQUEST"
export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS"
export const AUTH_LOGOUT_FAIL = "AUTH_LOGOUT_FAIL"

export const AUTH_REGISTER_REQUEST = "AUTH_REGISTER_REQUEST"
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS"
export const AUTH_REGISTER_FAIL = "AUTH_REGISTER_FAIL"

export const AUTH_GETALLUSER_REQUEST = "AUTH_GETALLUSER_REQUEST"
export const AUTH_GETALLUSER_SUCCESS = "AUTH_GETALLUSER_SUCCESS"
export const AUTH_GETALLUSER_FAIL = "AUTH_GETALLUSER_FAIL"

export const AUTH_GETONEUSER_REQUEST = "AUTH_GETONEUSER_REQUEST"
export const AUTH_GETONEUSER_SUCCESS = "AUTH_GETONEUSER_SUCCESS"
export const AUTH_GETONEUSER_FAIL = "AUTH_GETONEUSER_FAIL"

export const AUTH_UPDATE_REQUEST = "AUTH_UPDATE_REQUEST"
export const AUTH_UPDATE_SUCCESS = "AUTH_UPDATE_SUCCESS"
export const AUTH_UPDATE_FAIL = "AUTH_UPDATE_FAIL"

export const AUTH_CHANGEPW_REQUEST = "AUTH_CHANGEPW_REQUEST"
export const AUTH_CHANGEPW_SUCCESS = "AUTH_CHANGEPW_SUCCESS"
export const AUTH_CHANGEPW_FAIL = "AUTH_CHANGEPW_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"
