export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL";

export const AUTH_LOGOUT_REQUEST = "AUTH_LOGOUT_REQUEST";
export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS";
export const AUTH_LOGOUT_FAIL = "AUTH_LOGOUT_FAIL";

export const AUTH_REGISTER_REQUEST = "AUTH_REGISTER_REQUEST";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAIL = "AUTH_REGISTER_FAIL";

export const AUTH_GETALLUSER_REQUEST = "AUTH_GETALLUSER_REQUEST";
export const AUTH_GETALLUSER_SUCCESS = "AUTH_GETALLUSER_SUCCESS";
export const AUTH_GETALLUSER_FAIL = "AUTH_GETALLUSER_FAIL";

export const AUTH_GETONEUSER_REQUEST = "AUTH_GETONEUSER_REQUEST";
export const AUTH_GETONEUSER_SUCCESS = "AUTH_GETONEUSER_SUCCESS";
export const AUTH_GETONEUSER_FAIL = "AUTH_GETONEUSER_FAIL";

export const AUTH_UPDATE_REQUEST = "AUTH_UPDATE_REQUEST";
export const AUTH_UPDATE_SUCCESS = "AUTH_UPDATE_SUCCESS";
export const AUTH_UPDATE_FAIL = "AUTH_UPDATE_FAIL";

export const AUTH_CHANGEPW_REQUEST = "AUTH_CHANGEPW_REQUEST";
export const AUTH_CHANGEPW_SUCCESS = "AUTH_CHANGEPW_SUCCESS";
export const AUTH_CHANGEPW_FAIL = "AUTH_CHANGEPW_FAIL";

export const AUTH_DELETE_REQUEST = "AUTH_DELETE_REQUEST";
export const AUTH_DELETE_SUCCESS = "AUTH_DELETE_SUCCESS";
export const AUTH_DELETE_FAIL = "AUTH_DELETE_FAIL";

export const AUTH_FORGOTPW_REQUEST = "AUTH_FORGOTPW_REQUEST";
export const AUTH_FORGOTPW_SUCCESS = "AUTH_FORGOTPW_SUCCESS";
export const AUTH_FORGOTPW_FAIL = "AUTH_FORGOTPW_FAIL";

export const AUTH_UPDATENEWPW_REQUEST = "AUTH_UPDATENEWPW_REQUEST";
export const AUTH_UPDATENEWPW_SUCCESS = "AUTH_UPDATENEWPW_SUCCESS";
export const AUTH_UPDATENEWPW_FAIL = "AUTH_UPDATENEWPW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
