export const GET_ALL_BLOG_REQUIRED = "GET_ALL_BLOG_REQUIRED";
export const GET_ALL_BLOG_SUCCESS = "GET_ALL_BLOG_SUCCESS";
export const GET_ALL_BLOG_FAIL = "GET_ALL_BLOG_FAIL";

export const GET_ONE_BLOG_REQUIRED = "GET_ONE_BLOG_REQUIRED";
export const GET_ONE_BLOG_SUCCESS = "GET_ONE_BLOG_SUCCESS";
export const GET_ONE_BLOG_FAIL = "GET_ONE_BLOG_FAIL";

export const UPDATE_ONE_BLOG_REQUIRED = "UPDATE_ONE_BLOG_REQUIRED";
export const UPDATE_ONE_BLOG_SUCCESS = "UPDATE_ONE_BLOG_SUCCESS";
export const UPDATE_ONE_BLOG_FAIL = "UPDATE_ONE_BLOG_FAIL";

export const DELETE_ONE_BLOG_REQUIRED = "DELETE_ONE_BLOG_REQUIRED";
export const DELETE_ONE_BLOG_SUCCESS = "DELETE_ONE_BLOG_SUCCESS";
export const DELETE_ONE_BLOG_FAIL = "DELETE_ONE_BLOG_FAIL";

export const CREATE_ONE_BLOG_REQUIRED = "CREATE_ONE_BLOG_REQUIRED";
export const CREATE_ONE_BLOG_SUCCESS = "CREATE_ONE_BLOG_SUCCESS";
export const CREATE_ONE_BLOG_FAIL = "CREATE_ONE_BLOG_FAIL";
