// GET ALL CINEMA
export const ALL_CINEMA_REQUEST = "ALL_CINEMA_REQUEST"
export const ALL_CINEMA_SUCCESS = "ALL_CINEMA_SUCCESS"
export const ALL_CINEMA_FAIL = "ALL_CINEMA_FAIL"
// GET ONE CINEMA
export const ONE_CINEMA_REQUEST = "ONE_CINEMA_REQUEST"
export const ONE_CINEMA_SUCCESS = "ONE_CINEMA_SUCCESS"
export const ONE_CINEMA_FAIL = "ONE_CINEMA_FAIL"

export const CREATE_CINEMA_REQUEST = "CREATE_CINEMA_REQUEST"
export const CREATE_CINEMA_SUCCESS = "CREATE_CINEMA_SUCCESS"
export const CREATE_CINEMA_FAIL = "CREATE_CINEMA_FAIL"

export const DELETE_CINEMA_REQUEST = "DELETE_CINEMA_REQUEST"
export const DELETE_CINEMA_SUCCESS = "DELETE_CINEMA_SUCCESS"
export const DELETE_CINEMA_FAIL = "DELETE_CINEMA_FAIL"

export const UPDATE_CINEMA_REQUEST = "UPDATE_CINEMA_REQUEST"
export const UPDATE_CINEMA_SUCCESS = "UPDATE_CINEMA_SUCCESS"
export const UPDATE_CINEMA_FAIL = "UPDATE_CINEMA_FAIL"