// GET ALL CINEMA
export const ALL_CINEMA_REQUEST = "ALL_CINEMA_REQUEST"
export const ALL_CINEMA_SUCCESS = "ALL_CINEMA_SUCCESS"
export const ALL_CINEMA_FAIL = "ALL_CINEMA_FAIL"
// GET ONE CINEMA
export const ONE_CINEMA_REQUEST = "ONE_CINEMA_REQUEST"
export const ONE_CINEMA_SUCCESS = "ONE_CINEMA_SUCCESS"
export const ONE_CINEMA_FAIL = "ONE_CINEMA_FAIL"