export const GET_ALL_EVENT_REQUIRED = "GET_ALL_EVENT_REQUIRED";
export const GET_ALL_EVENT_SUCCESS = "GET_ALL_EVENT_SUCCESS";
export const GET_ALL_EVENT_FAIL = "GET_ALL_EVENT_FAIL";

export const GET_ONE_EVENT_REQUIRED = "GET_ONE_EVENT_REQUIRED";
export const GET_ONE_EVENT_SUCCESS = "GET_ONE_EVENT_SUCCESS";
export const GET_ONE_EVENT_FAIL = "GET_ONE_EVENT_FAIL";

export const CREATE_EVENT_REQUIRED = "CREATE_EVENT_REQUIRED";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const CREATE_EVENT_FAIL = "CREATE_EVENT_FAIL";

export const DELETE_EVENT_REQUIRED = "DELETE_EVENT_REQUIRED";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAIL = "DELETE_EVENT_FAIL";

export const UPDATE_EVENT_REQUIRED = "UPDATE_EVENT_REQUIRED";
export const UPDATE_EVENT_SUCCESS = "UPDATE_EVENT_SUCCESS";
export const UPDATE_EVENT_FAIL = "UPDATE_EVENT_FAIL";
