export const GET_ALL_EVENT_REQUIRED = "GET_ALL_EVENT_REQUIRED"
export const  GET_ALL_EVENT_SUCCESS = "GET_ALL_EVENT_SUCCESS"
export const  GET_ALL_EVENT_FAIL = "GET_ALL_EVENT_FAIL"

export const GET_ONE_EVENT_REQUIRED = "GET_ONE_EVENT_REQUIRED"
export const  GET_ONE_EVENT_SUCCESS = "GET_ONE_EVENT_SUCCESS"
export const  GET_ONE_EVENT_FAIL = "GET_ONE_EVENT_FAIL"










