export const POST_FEEDBACK_REQUIRED = "POST_FEEDBACK_REQUIRED"
export const POST_FEEDBACK_SUCCESS = "POST_FEEDBACK_SUCCESS"
export const POST_FEEDBACK_FAIL = "POST_FEEDBACK_FAIL"

export const ALL_FEEDBACK_REQUIRED = "ALL_FEEDBACK_REQUIRED"
export const ALL_FEEDBACK_SUCCESS = "ALL_FEEDBACK_SUCCESS"
export const ALL_FEEDBACK_FAIL = "ALL_FEEDBACK_FAIL"

export const SEND_FEEDBACK_REQUIRED = "SEND_FEEDBACK_REQUIRED"
export const SEND_FEEDBACK_SUCCESS = "SEND_FEEDBACK_SUCCESS"
export const SEND_FEEDBACK_FAIL = "SEND_FEEDBACK_FAIL"








