// GET ALL FOOD
export const ALL_FOOD_REQUEST = "ALL_FOOD_REQUEST"
export const ALL_FOOD_SUCCESS = "ALL_FOOD_SUCCESS"
export const ALL_FOOD_FAIL = "ALL_FOOD_FAIL"

export const INCREMENT_FOOD = "INCREMENT_FOOD"
export const DECREMENT_FOOD = "DECREMENT_FOOD"