// GET ALL FOOD
export const ALL_FOOD_REQUEST = "ALL_FOOD_REQUEST"
export const ALL_FOOD_SUCCESS = "ALL_FOOD_SUCCESS"
export const ALL_FOOD_FAIL = "ALL_FOOD_FAIL"

export const ONE_FOOD_REQUEST = "ONE_FOOD_REQUEST"
export const ONE_FOOD_SUCCESS = "ONE_FOOD_SUCCESS"
export const ONE_FOOD_FAIL = "ONE_FOOD_FAIL"

export const INCREMENT_FOOD = "INCREMENT_FOOD"
export const DECREMENT_FOOD = "DECREMENT_FOOD"

export const CREATE_FOOD_REQUEST = "CREATE_FOOD_REQUEST"
export const CREATE_FOOD_SUCCESS = "CREATE_FOOD_SUCCESS"
export const CREATE_FOOD_FAIL = "CREATE_FOOD_FAIL"

export const DELETE_FOOD_REQUEST = "DELETE_FOOD_REQUEST"
export const DELETE_FOOD_SUCCESS = "DELETE_FOOD_SUCCESS"
export const DELETE_FOOD_FAIL = "DELETE_FOOD_FAIL"

export const UPDATE_FOOD_REQUEST = "UPDATE_FOOD_REQUEST"
export const UPDATE_FOOD_SUCCESS = "UPDATE_FOOD_SUCCESS"
export const UPDATE_FOOD_FAIL = "UPDATE_FOOD_FAIL"