// GET ALL MOVIESOON
export const ALL_MOVIESOON_REQUEST = "ALL_MOVIESOON_REQUEST"
export const ALL_MOVIESOON_SUCCESS = "ALL_MOVIESOON_SUCCESS"
export const ALL_MOVIESOON_FAIL = "ALL_MOVIESOON_FAIL"

// GET ONE MOVIESOON ID

export const ONE_MOVIESOON_REQUEST = "ONE_MOVIESOON_REQUEST"
export const ONE_MOVIESOON_SUCCESS = "ONE_MOVIESOON_SUCCESS"
export const ONE_MOVIESOON_FAIL = "ONE_MOVIESOON_FAIL"

export const CREATE_MOVIESOON_REQUEST = "CREATE_MOVIESOON_REQUEST"
export const CREATE_MOVIESOON_SUCCESS = "CREATE_MOVIESOON_SUCCESS"
export const CREATE_MOVIESOON_FAIL = "CREATE_MOVIESOON_FAIL"

export const DELETE_MOVIESOON_REQUEST = "DELETE_MOVIESOON_REQUEST"
export const DELETE_MOVIESOON_SUCCESS = "DELETE_MOVIESOON_SUCCESS"
export const DELETE_MOVIESOON_FAIL = "DELETE_MOVIESOON_FAIL"

export const UPDATE_MOVIESOON_REQUEST = "UPDATE_MOVIESOON_REQUEST"
export const UPDATE_MOVIESOON_SUCCESS = "UPDATE_MOVIESOON_SUCCESS"
export const UPDATE_MOVIESOON_FAIL = "UPDATE_MOVIESOON_FAIL"