// GET ALL MOVIESOON
export const ALL_MOVIESOON_REQUEST = "ALL_MOVIESOON_REQUEST"
export const ALL_MOVIESOON_SUCCESS = "ALL_MOVIESOON_SUCCESS"
export const ALL_MOVIESOON_FAIL = "ALL_MOVIESOON_FAIL"

// GET ONE MOVIESOON ID

export const ONE_MOVIESOON_REQUEST = "ONE_MOVIESOON_REQUEST"
export const ONE_MOVIESOON_SUCCESS = "ONE_MOVIESOON_SUCCESS"
export const ONE_MOVIESOON_FAIL = "ONE_MOVIESOON_FAIL"
