// GET ALL MOVIE
export const ALL_MOVIE_REQUEST = "ALL_MOVIE_REQUEST"
export const ALL_MOVIE_SUCCESS = "ALL_MOVIE_SUCCESS"
export const ALL_MOVIE_FAIL = "ALL_MOVIE_FAIL"

// GET ONE MOVIE ID

export const ONE_MOVIE_REQUEST = "ONE_MOVIE_REQUEST"
export const ONE_MOVIE_SUCCESS = "ONE_MOVIE_SUCCESS"
export const ONE_MOVIE_FAIL = "ONE_MOVIE_FAIL"

export const CREATE_MOVIE_REQUEST = "CREATE_MOVIE_REQUEST"
export const CREATE_MOVIE_SUCCESS = "CREATE_MOVIE_SUCCESS"
export const CREATE_MOVIE_FAIL = "CREATE_MOVIE_FAIL"

export const DELETE_MOVIE_REQUEST = "DELETE_MOVIE_REQUEST"
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS"
export const DELETE_MOVIE_FAIL = "DELETE_MOVIE_FAIL"

export const UPDATE_MOVIE_REQUEST = "UPDATE_MOVIE_REQUEST"
export const UPDATE_MOVIE_SUCCESS = "UPDATE_MOVIE_SUCCESS"
export const UPDATE_MOVIE_FAIL = "UPDATE_MOVIE_FAIL"
