export const CREATE_RESERVATION_REQUEST = "CREATE_RESERVATION_REQUEST"
export const CREATE_RESERVATION_SUCCESS = "CREATE_RESERVATION_SUCCESS"
export const CREATE_RESERVATION_FAIL = "CREATE_RESERVATION_FAIL"

export const ONE_RESERVATION_REQUEST = "ONE_RESERVATION_REQUEST"
export const ONE_RESERVATION_SUCCESS = "ONE_RESERVATION_SUCCESS"
export const ONE_RESERVATION_FAIL = "ONE_RESERVATION_FAIL"

export const ALL_RESERVATION_REQUEST = "ALL_RESERVATION_REQUEST"
export const ALL_RESERVATION_SUCCESS = "ALL_RESERVATION_SUCCESS"
export const ALL_RESERVATION_FAIL = "ALL_RESERVATION_FAIL"

export const UPDATE_RESERVATION_REQUEST = "UPDATE_RESERVATION_REQUEST"
export const UPDATE_RESERVATION_SUCCESS = "UPDATE_RESERVATION_SUCCESS"
export const UPDATE_RESERVATION_FAIL = "UPDATE_RESERVATION_FAIL"

export const DELETE_RESERVATION_REQUEST = "DELETE_RESERVATION_REQUEST"
export const DELETE_RESERVATION_SUCCESS = "DELETE_RESERVATION_SUCCESS"
export const DELETE_RESERVATION_FAIL = "DELETE_RESERVATION_FAIL"

