export const ALL_SEAT_REQUEST = "ALL_SEAT_REQUEST";
export const ALL_SEAT_SUCCESS = "ALL_SEAT_SUCCESS";
export const ALL_SEAT_FAIL = "ALL_SEAT_FAIL";

export const ONE_SEAT_REQUEST = "ONE_SEAT_REQUEST";
export const ONE_SEAT_SUCCESS = "ONE_SEAT_SUCCESS";
export const ONE_SEAT_FAIL = "ONE_SEAT_FAIL";

export const UPDATE_STATUS_REQUEST = "UPDATE_STATUS_REQUEST";
export const UPDATE_STATUS_SUCCESS = "UPDATE_STATUS_SUCCESS";
export const UPDATE_STATUS_FAIL = "UPDATE_STATUS_FAIL";

export const CREATE_SEAT_REQUEST = "CREATE_SEAT_REQUEST";
export const CREATE_SEAT_SUCCESS = "CREATE_SEAT_SUCCESS";
export const CREATE_SEAT_FAIL = "CREATE_SEAT_FAIL";

export const UPDATE_SEAT_REQUEST = "UPDATE_SEAT_REQUEST";
export const UPDATE_SEAT_SUCCESS = "UPDATE_SEAT_SUCCESS";
export const UPDATE_SEAT_FAIL = "UPDATE_SEAT_FAIL";
