// GET ALL SEAT
export const ALL_SEAT_REQUEST = "ALL_SEAT_REQUEST"
export const ALL_SEAT_SUCCESS = "ALL_SEAT_SUCCESS"
export const ALL_SEAT_FAIL = "ALL_SEAT_FAIL"

// GET ONE SEAT ID

export const ONE_SEAT_REQUEST = "ONE_SEAT_REQUEST"
export const ONE_SEAT_SUCCESS = "ONE_SEAT_SUCCESS"
export const ONE_SEAT_FAIL = "ONE_SEAT_FAIL"

// UPDATE STATUS SEAT

export const UPDATE_STATUS_REQUEST = "UPDATE_STATUS_REQUEST"
export const UPDATE_STATUS_SUCCESS = "UPDATE_STATUS_SUCCESS"
export const UPDATE_STATUS_FAIL = "UPDATE_STATUS_FAIL"



