// GET ALL SHOWTIME
export const ALL_SHOWTIME_REQUEST = "ALL_SHOWTIME_REQUEST"
export const ALL_SHOWTIME_SUCCESS = "ALL_SHOWTIME_SUCCESS"
export const ALL_SHOWTIME_FAIL = "ALL_SHOWTIME_FAIL"

// GET ONE SHOWTIME
export const ONE_SHOWTIME_REQUEST = "ONE_SHOWTIME_REQUEST"
export const ONE_SHOWTIME_SUCCESS = "ONE_SHOWTIME_SUCCESS"
export const ONE_SHOWTIME_FAIL = "ONE_SHOWTIME_FAIL"
