// GET ALL SHOWTIME
export const ALL_SHOWTIME_REQUEST = "ALL_SHOWTIME_REQUEST"
export const ALL_SHOWTIME_SUCCESS = "ALL_SHOWTIME_SUCCESS"
export const ALL_SHOWTIME_FAIL = "ALL_SHOWTIME_FAIL"

// GET ONE SHOWTIME
export const ONE_SHOWTIME_REQUEST = "ONE_SHOWTIME_REQUEST"
export const ONE_SHOWTIME_SUCCESS = "ONE_SHOWTIME_SUCCESS"
export const ONE_SHOWTIME_FAIL = "ONE_SHOWTIME_FAIL"

export const CREATE_SHOWTIME_REQUEST = "CREATE_SHOWTIME_REQUEST"
export const CREATE_SHOWTIME_SUCCESS = "CREATE_SHOWTIME_SUCCESS"
export const CREATE_SHOWTIME_FAIL = "CREATE_SHOWTIME_FAIL"

export const DELETE_SHOWTIME_REQUEST = "DELETE_SHOWTIME_REQUEST"
export const DELETE_SHOWTIME_SUCCESS = "DELETE_SHOWTIME_SUCCESS"
export const DELETE_SHOWTIME_FAIL = "DELETE_SHOWTIME_FAIL"

export const UPDATE_SHOWTIME_REQUEST = "UPDATE_SHOWTIME_REQUEST"
export const UPDATE_SHOWTIME_SUCCESS = "UPDATE_SHOWTIME_SUCCESS"
export const UPDATE_SHOWTIME_FAIL = "UPDATE_SHOWTIME_FAIL"