// GET ALL TICKET
export const ALL_TICKET_REQUEST = "ALL_TICKET_REQUEST"
export const ALL_TICKET_SUCCESS = "ALL_TICKET_SUCCESS"
export const ALL_TICKET_FAIL = "ALL_TICKET_FAIL"

// GET ONE TICKET
export const ONE_TICKET_REQUEST = "ONE_TICKET_REQUEST"
export const ONE_TICKET_SUCCESS = "ONE_TICKET_SUCCESS"
export const ONE_TICKET_FAIL = "ONE_TICKET_FAIL"

export const INCREMENT = "INCREMENT"
export const DECREMENT = "DECREMENT"