// GET ALL TICKET
export const ALL_TICKET_REQUEST = "ALL_TICKET_REQUEST"
export const ALL_TICKET_SUCCESS = "ALL_TICKET_SUCCESS"
export const ALL_TICKET_FAIL = "ALL_TICKET_FAIL"

// GET ONE TICKET
export const ONE_TICKET_REQUEST = "ONE_TICKET_REQUEST"
export const ONE_TICKET_SUCCESS = "ONE_TICKET_SUCCESS"
export const ONE_TICKET_FAIL = "ONE_TICKET_FAIL"

export const INCREMENT = "INCREMENT"
export const DECREMENT = "DECREMENT"

export const CREATE_TICKET_REQUEST = "CREATE_TICKET_REQUEST"
export const CREATE_TICKET_SUCCESS = "CREATE_TICKET_SUCCESS"
export const CREATE_TICKET_FAIL = "CREATE_TICKET_FAIL"

export const DELETE_TICKET_REQUEST = "DELETE_TICKET_REQUEST"
export const DELETE_TICKET_SUCCESS = "DELETE_TICKET_SUCCESS"
export const DELETE_TICKET_FAIL = "DELETE_TICKET_FAIL"